conrad-blucher-institute/semaphore

data/dspec/test_dspec.json
src/ModelExecution/inputGatherer.py
src/SeriesProvider/SeriesProvider.py
src/SeriesStorage/SeriesStorage/SS_SQLLite.py

This turned out not to be a bug, but a complication of how we were doing things. Let me show you this graph.
I hope that worked! If not ill put it in the discord. Basically though, if you just take time range * interval, you create a block of time. The red rectangle. If its offset from the hour mark, then you get 12 hours of data points. However, if you back it up to the hour mark you get 13. This is a problem though as we would be expecting 12 data points and get 13 sometimes. Hence our bug.
The fix for this is basically just saying models have to be run at their iteration time. So if the model is hourly it HAS to be run on the hour (or the datepoint supplied must be on the hour). Basically we need to do it this way such that the DSPEC files and clearly communicate weather they want 12 …

Fixing 00 "bug"

---

src/SeriesProvider/SeriesProvider.py
src/SeriesStorage/SeriesStorage/SQLLite.py

So the issue was two things. First the test case had issues. An attribute was wrong and the date time was quering for the generated time not varification time. Secondly the way I was trying to calculate those in the query, did not work. So I fixed that for both quering outputs and predictions.

69 bug with lead time and time generated calculation

---

src/SeriesStorage/SeriesStorage/SQLAlchemyORM.py

Added datum back to AK for inputs table
Made datum not nullable
Datum is still optional for semaphore, just not for the DB. However this is fine as our data structures set datum to null if its not provided

Readded datum for AK for inputs table, but datum is now required

---

src/ModelExecution/OutputHandler/OnePackedFloat.py
src/ModelExecution/modelWrapper.py

- Only LIGHTHOUSE test is failing, but I think that is a LIGHTHOUSE issue.
- I REALLY wanted to refactor the whole generatedTime -> referenceTime thing, but it seems like it would do more harm than good right now. Will add it as a backlog ticket.

Now passing referenceTime to post_process_predition

---

.env.dist
docker-compose.yml

Now, you must define your `POSTGRES_USER`, `POSTGRES_PASSWORD`, and `POSTGRES_DB` as actual .env variables. See `.env.dist`. This means that you must also change your `DB_LOCATION_STRING` to match your credentials. You may also want to change your `DB_HOST_PORT` to avoid any port conflicts (in case two users run the containers at the same time.)
 
You can connect to the DB from your local pgAdmin app like so:
You must be connected to the TAMUCC VPN. The port, username, and password must all match what you put in your .env.
(*NOTE:: If you ran the containers on sherlock before you will need to remove the `psql-data` volume by using `docker volume rm psql-data` such that you can initialize your new username and password.)

Added extra_hosts to docker-compose file

---

data/dspec/MLP-OP.json
data/dspec/ThermalRefuge.json

I think that really there was only the one remnant of the old dspec in MLP with the dataClassification, everything else was included in the despc.py file. I wasn't completely sure what timing info to put for the thermal refuge so I just put hourly.

added timing info where needed and removed dataClasification

---

src/DataIngestion/DataIngestion/LIGHTHOUSE.py

LIGHTHOUSE was crashing when the PD returned only nulls. When we tried to insert the empty list into the DB the crash happens. I fixed this by having the LIGHTHOUSE class check and see if no good inputs were found, and if so, it does not insert into the DB and logs what happened.

Fixing crash on LIGHTHOUSE returning all null values

---

src/DataIngestion/DI_Classes/NDBC.py
src/DataIngestion/DI_Classes/NOAATANDC.py

Fixed by filtering any nones from lists before preforming the sum operation.
The sum operation returns Nan if non numeric data is within the list.
We clear Nones before selecting the four max to make sure we select the 4 highest values that we actually have.

Fixing NAN 4mm bug

---

data/dspec/Magnolia/magnolia_transform_24.json
src/DataIngestion/DI_Classes/SEMAPHORE.py

```python
import sys
sys.path.append('/app/src')
import pytest
from datetime import datetime, timedelta, time, date
from src.DataClasses import TimeDescription, SeriesDescription
from src.DataIngestion.IDataIngestion import data_ingestion_factory
from src.DataIngestion.DI_Classes.LIGHTHOUSE import LIGHTHOUSE
from dotenv import load_dotenv
load_dotenv()
sd = SeriesDescription("SEMAPHORE", "test AI|1.0.0|testSeries", 'packChan', "test_datum") 
td = TimeDescription(datetime.combine(date(2024, 4, 28), time(0, 0)), datetime.combine(date(2024, 4, 30), time(12, 0)), timedelta(seconds=3600))
lighthouse = data_ingestion_factory(sd)
result = lighthouse.ingest_series(sd, td)
print(result)
print(result.data)
```
Code provided for testing. I didnt make this into a test as that would rely on DB data. …

290 create semaphore ingestion class

---

src/PostProcessing/IPostProcessing.py

This is very much a patchwork fix. I went to a friend about this. She said that its likely systemic of me having used `from foo import *` Basically she thinks `import foo` should have been used instead. This helps break circular imports. This solution will work for now though.

Fixing circular imports

---

data/dspec/Magnolia/48/magnolia_transform_48.json

Currently isn't making predictions, because it thinks the dataIntegrityDescription is None. When dataIntegrityDescription is None it returns the unaltered series.

Deactivated magnolia transform 48h

---

requirements.txt

This doesn't seem correct, but it is whats running on sherlock dev.

363 edit requirementstxt

---

src/DataIngestion/DI_Classes/TEST_DI.py
src/SeriesProvider/SeriesProvider.py
src/SeriesStorage/SS_Classes/TEST_SS.py
src/tests/IntegrationTests/test_SeriesProvider.py
src/tests/UnitTests/test_unit_SeriesProvider.py

Okay, this started with a bug, that if an ingestion class returned an empty series that Series Provider would try and insert it into the DB causing a weird DB error.
In isolation that's a very simple bug fix, but this is the third bug ive fixed in series provider THIS WEEK. The fact is it had some issues. There were some architecture issues with how data was being handled and inserted and it was just incredibly unreadable and had awful tests.
Thus I refactored it to improve its readability and reworked how series provider sends data to get inserted. I wrote a mock data ingestion class and a mock series storage class and reworked the unit testing for series provider.
To test this (and please run through this with a fine tooth comb less we be back here next week to fix another bug):
1. …

Series provider refector w/ tests

---

src/DataIngestion/DI_Classes/NDBC.py

**Background:** 
For a period of time from late July to mid August semaphore experienced an 'index out of range' error. Because the error has only been observed within that time frame no further investigation was done, however it seemed like a good idea to add a small logging statement for when NDBC returns no data in order to provide future debuggers with more information/context. 
I just did a simple statement and added a comment about why it's likely an error on NDBC's side. Very open to changes that align the log more with what is appropriate to log. 
**To Test:** 
Run a model that uses NDBC to make sure the statement doesn't trigger when data is returned: 
`docker exec semaphore-core python3 src/semaphoreRunner.py -d Inundation/August/ar_inundation_aug_12h.json`
Run a model from the …

Logging NDBC Error

---

src/API/apiDriver.py
src/DataIngestion/DI_Classes/SEMAPHORE.py
src/SeriesProvider/SeriesProvider.py
src/SeriesStorage/ISeriesStorage.py
src/SeriesStorage/SS_Classes/SQLAlchemyORM_Postgres.py
src/SeriesStorage/SS_Classes/TEST_SS.py
src/tests/IntegrationTests/test_SeriesProvider.py

~~I added a new endpoint called /latest_ouputs its queries outputs based just on a model name and time range, inferring things like model version and lead time based on the latest model version in the db and the latest ouput from that model.~~
~~As a note swaggy ui, what fast api uses for its docs seems to have a bug or something rn, idk I didnt super look into it, but testing through the docs page isn't working. You can use this instead, just make sure you fill it out correctly~~
~~`curl 'http://localhost:8888/semaphore-api/latest_outputs/modelName=ar_inundation_apr_12h/fromDateTime=2024101618/toDateTime=2024101819'  -H 'accept: application/json' -v`~~

latest outputs endpoint

---

src/ModelExecution/dspecParser.py

I never added indexing to the 1.0 parser it was causing the 1.0 dspecs to fail. This bug patches that, easily testable.
1. Build and run
2. `docker exec semaphore-core python3 src/semaphoreRunner.py -d ThermalRefuge.json`

Adding indexes to 1.0 parser

---

src/DataIngestion/DI_Classes/NOAATANDC.py
src/tests/IntegrationTests/test_NOAATANDC.py

This PR adds cases to NOAATANDC that handle actual air and water temperature.
1. Remove the statement in test_NOAATANDC that skips the test.
2. Run the tests: docker exec semaphore-core python3 -m pytest -s
I added a print statement to show the data. While it may look messy when testing all tests, the ingestion classes are usually skipped anyway. When testing ingestion classes individually, printing the data is helpful to ensure the data is correct.
The first screenshots are the data from the test and the last 3 screen shots is data from NOAATANDC. This verifies that the correct data is being retrieved from NOAATANDC. Convert from Celsius to Fahrenheit. ATMP is Air Temperature and WTMP is Water Temperature.

Added cases that handle actual air and water temperature from NOAATANDC

---

src/API/apiDriver.py
src/SeriesProvider/SeriesProvider.py

When attempting to fetch inputs for the measurements displayed on the Laguna Madre the Semaphore API returns an "Internal Server Error". After further investigation we've found that the API is giving: 2025-01-10 13:52:06 semaphore-api   | ValueError: Out of range float values are not JSON compliant when we attempt to return the inputs from series provider to the API as a JSON object. We've found that this is because there are a small number of nans returned in the data and FastAPI's jsonable_encoder
does not allow nans in the jason object that it returns to the user. 
Our solution was to add a check for nans in the API driver and swap the nans into Nones which FastAPI's jsonable_encoder can parse/remove on it's own. Meaning that the response body that the user gets will exclude the …

508 semaphore api returns internal server error when attempting to fetch inputs for flare graph

---

tools/DatabaseMigration/2_9/2_9_DatabaseMigration.py
tools/DatabaseMigration/databaseMigrationUtility.py

I added a function that specifically deletes rows from mapping without deleting rows from other reference tables. It uses both dataLocation and dataSource since there are many locations with the same name, but different sources.
Step 1: Build the docker containers
- `docker compose down`
- `docker compose build`
- `docker compose up -d`
Step 2: Open pgadmin and check the datasource_datalocation_mapping table. If you are on version 2.9 there will be a lagunamadre - NDFD_EXP mapping. at the bottom.
Step 3: Change the target version in Semaphore to 2.8 to test roll back from 2.9 to 2.8 
Step 4: Build the docker containers
Step 5: Run this command: `docker exec semaphore-core python3 ./tools/migrate_db.py`
Step 6: Close the datasource_datalocation_mapping table tab that you have open and …

Fixed the 2.9 rollback and added a function that deletes rows from mapping

---

tools/DatabaseMigration/2_10/2_10_DatabaseMigration.py
tools/DatabaseMigration/2_11/2_11_DatabaseMigration.py
tools/DatabaseMigration/target_version.json
tools/migrate_db.py

THis database migration updates the laguna madre location lat and long and includes Matthews fix for the database migration versions error. 
How to test (Make sure you start at version 2.9):
Step 1: Build the docker containers
- docker compose down
- docker compose build
- docker compose up -d
Step 2: Open pgadmin and check the datalocation table. If you are on version 2.9 the laguna madre location will have a 0 for lat and long.
Step 3: Change the target version in Semaphore to 2.10
Step 4: Build the docker containers
Step 5: Run this command: docker exec semaphore-core python3 ./tools/migrate_db.py
Step 6: Close the datalocation table tab that you have open and refresh the database.
- Right click the database to refresh
Step 7: Check the table again and the laguna madre latitude=26.75, …

41 database migration 2 11

---

src/SeriesProvider/SeriesProvider.py

This is harder to test.
- Run an API query with not interval requested
- Run some models
Most of the time interval is explicitly requested. CBOCP does request hourly data explicitly so no matter what thats safe.

Changing assumed interval from 6min to 1hour

---

src/DataIngestion/DI_Classes/NDFD_EXP.py
src/exceptions.py

This addition will add a function that validates the time passed to NDFD_EXP.
How to test:
- Build containers
- Use this URL to test that the function returns false if either datetimes are in the past: http://localhost:8888/docs

523 prediction requests in ndfd throw xml error when dates are in the past

---

src/DataClasses.py
src/tests/UnitTests/test_DataClasses.py

Has been modified to handle both single float values and lists of float values for input and output. Now, if a single float is provided, it is treated as such. If a list of floats is provided, it will be processed as a list. So, even if a single value is wrapped in an array, it will no longer cause issues and should be able to handle both cases appropriately.
***
Has been modified to test single float values and list of float values for input and output but was also updated to test other classes within the DataClasses file.
***
docker-compose up -d --build
docker exec semaphore-core python3 tools/migrate_db.py
docker exec semaphore-core python -m pytest
***
When running test, one test does fail but, test is from test_inputGatherer test and is most likely not from anything added by us
Sav …

553 refactor input and output objects

---

src/API/apiDriver.py

A fix for the error where when requesting TWC data we would get a `ValueError: Out of range float values are not JSON compliant`.  This fix changes it so that we make the dictionary, replace NaN's with None and then encode the response because unlike NaNs, None's can be handled by the encoder. 
To Test: 
- Build and run containers. 
- Visit local API: [Input Request](http://localhost:8888/docs#/default/get_input_input_source__source__series__series__location__location__fromDateTime__fromDateTime__toDateTime__toDateTime__get)
- Request TPW data similar to below screenshot but altered to use timestamps int he future:

API TWC Error

---

tools/deploy.sh

Updating Semaphores deployment script to match version 28 of docker which doesn't use the dash in 'docker-compose'
using 'docker compose' now instead of 'docker-compose'
docker compose build
docker compose up -d
docker exec semaphore-core python3 tools/migrate_db.py
LMK if i did anything wrong :)

docker deploy

---

src/orchestrator.py

The missing entries are caused by lists of dspecs being run in a loop. This loop was nested into a try block, meaning if any model failed the try block would catch it and control flow never returns back to the loop. Ergo the fix was to move the loop out of the try block.
To test you can mess up a dspec in one of the job so it will crash, and notice that all the models still get run

Im a big dummy dumb dumb

---

src/DataIngestion/DI_Classes/TWC.py

To run:
1. docker compose down
2. docker compose up --build -d
3. go to http://localhost:8888/docs#/default/get_input_input_source__source__series__series__location__location__fromDateTime__fromDateTime__toDateTime__toDateTime__get
4. fill in required fields
5. check the output in dataValue: [...]. Celsius values should be around high 20's and low 30's
I recommend copy and pasting a dataValue block into an AI to find the median and convert it to fahrenheit to see that the temperatures are much higher now.

Removed $ from lat/long in url

---

tools/DatabaseMigration/3_2/3_2_DatabaseMigration.py
tools/DatabaseMigration/target_version.json

- Deletes null timeGenerated rows ininputs
- Makes timeGenerated non Null
- Build containers: `docker compose up --build -d`
- Open pgadmin and take a look at null timeGenerated rows in inputs.
- Right click inputs in pgadmin go to properties and see that timeGenerated does not have Not Null Clicked.
- Migrate the db: `docker exec semaphore-core python3 ./tools/migrate_db.py`
- Redo 2 and 3. Nulls in timeGenerated should be gone and the Not Null mark should be clicked.
== Roll Back ==
- Change the target version to 3.1
- Build containers: `docker compose up --build -d`
- Migrate db: `docker exec semaphore-core python3 ./tools/migrate_db.py`
- The Not Null Mark shopuld be ticked back off.

db migration 3.2

---

src/DataIngestion/DI_Classes/TWC.py
src/tests/UnitTests/test_TWC.py

TWC does not give an explicit generated time, so we will use initTime extracted from the metadata. Only a single initTime is given, so all rows use the same initTime. This then gets converted using .utcfromtimestamp( ) to get our generatedTime.
- TWC ingestion class now sets generated time as the returned initTime from the response
- updated unit tests to include an initTime key/value pair 
- added an assertion loop to ensure all rows have the same timeGenerated set
- `docker compose down`
- `docker compose up --build -d`
- `docker exec semaphore-core python3 -m pytest -v` 
- All tests should pass (except the 2 model_runner assertion tests that fail due to the trailing decimal if you get them).

691 twc sets generated time

---

src/DataIngestion/DI_Classes/LIGHTHOUSE.py
src/tests/IntegrationTests/test_LIGHTHOUSE.py

- Removed dropping nulls
- Removed interval formatting
- Corrected deprecated functions
- Remove line 27 in the Lighthouse test
- docker compose down --volumes
- Build containers: docker compose up --build -d
- docker exec semaphore-core python3 tools/migrate_db.py
- Run Tests: docker exec semaphore-core python3 -m pytest -s
- docker exec semaphore-core python3 src/semaphoreRunner.py -d ./data/dspec/Magnolia/12/magnolia_12.json
NOTE:  Ignore "Can't convert to float: None" error. This is caused by dropping the handling of None in lighthouse.
Make sure this error isnt seen.
Why did you remove UTC in the timestamp?
- The original function (utcfromtimestamp) returned a UTC timestamp that was timezone-naive. The updated approach (fromtimestamp(..., tz=timezone.utc)) creates a timezone-aware …

Removed data manipulation from lighthouse
