- src/SeriesStorage/SeriesStorage/SQLLite.py
I removed the check completely there by letting requests not cause the error.
> Removing the check completely

- src/ModelExecution/inputGatherer.py
- src/tests/test_InputGatherer.py
Test doesn't work yet but should work once SeriesProvider is refactored.
> 102 refactor inputgatherer to use new data objects and request format

- requirements.txt
- src/API/apiDriver.py
- src/API/datetime_handler.py
- src/tests/test_API.py
Test doesn't work yet but should work once SeriesProvider is refactored.
> 104 refactor api endpoints

- data/dspec/MLP-OP.json
- src/DataIngestion/DataIngestion/LIGHTHOUSE.py
- src/tests/test_LIGHTHOUSE.py
Make sure you have this mapping row to preform the tests
`insert_external_location_code('SouthBirdIsland', 'LIGHTHOUSE', '013', 0)`
> 79 create tcoon lighthouse ingestion class

- .dockerignore
Based it mostly off of the .gitignore file and what I saw online.
- docs and db were already on there. What are they for?
- Let me know what doesn't need to be ignored and what is missing.
> Updated .dockerignore

- data/dspec/MLP-OP.json
- src/tests/test_SQLAlchemyORM.py
Edit Locations
WTP: South bird island -> NPSBI National Park Main Station (171, NPSBI)
ATP: South bird island -> pack channel (005, PACKER)
> added two new stations to cold stunning dspec

- src/ModelExecution/modelWrapper.py
- src/semaphoreRunner.py
Running without the toss flag stores the prediction in the DB
Running with the toss flag prevents storage in the DB
> 168 entry point has argument to not save the computed value

- src/DataIngestion/DataIngestion/NDFD.py
- src/tests/test_NDFD.py
- Please read the comments I added and inspect the logic closely!
> Added logic to handle missing toDateTime in NDFD

- data/cron/semaphore.cron
Quick fix adding comments and a line to add the thermal refuge model.
> adding comments and thermal refuge model

- src/SeriesProvider/SeriesProvider.py
- src/tests/IntegrationTests/test_SeriesProvider.py
- src/tests/UnitTests/test_unit_SeriesProvider.py
Creating this request so I can comment directly in the code
> 193 update series provider merge method

- src/ModelExecution/modelWrapper.py
- src/SeriesProvider/SeriesProvider.py
- src/semaphoreRunner.py
The DB errors weren't being reported not because they were caught but because they weren't caught. I added a proper try except case at the very top of running semaphore, in semaphoRerunner.py. That way we will be logging these errors.
I also added logging at major points
Blocked by merge method PR: 193
> 209 add better logging

- docker-compose.yml
- tools/HEALTHCHECK_CORE.py
Created a HealthCheck for semaphore core that connects to the database and performs a test query
> created healthcheck for semaphore core

- src/SeriesProvider/SeriesProvider.py
- src/semaphoreRunner.py
Fixed by checking if its none before we try and access data
> 215 series provider remake not handling nones correctly

- data/cron/semaphore.cron
- src/SeriesProvider/SeriesProvider.py
- src/utility.py
I revised the series log description, updated the cron job to organize files by month and year, established paths for the logs, and removed the manual addition of messages to a `log.txt` file from the `log` function since it's redundant—cron already appends the output to the file.
> Logs fixed

- requirements.txt
We froze tf before because of a bug. The big has been fixed,  so now I will unfreeze tf again.
> Unfreeze TF

- data/dspec/Magnolia/magnolia_24.json
- data/dspec/Magnolia/magnolia_transform_24.json
- src/PostProcessing/PostProcessingClasses/ResolveVectorComponents.py
- src/tests/UnitTests/test_ResolveVectorComponents.py
Test command:
```bash
docker exec semaphore-core python3 -m pytest ./src/tests/UnitTests/test_ResolveVectorComponents.py
```
I renamed a thing to keep the class generalized:
[Computing vector components is called resolving](http://hyperphysics.phy-astr.gsu.edu/hbase/vect.html)
> 285 create the dywinds and the dxwinds post processing class

- data/dspec/Magnolia/magnolia_24.json
- data/dspec/Magnolia/magnolia_transform_24.json
- src/PostProcessing/PostProcessingClasses/Average.py
- src/PostProcessing/PostProcessingClasses/ResolveVectorComponents.py
- src/tests/UnitTests/test_Average.py
- src/tests/UnitTests/test_ResolveVectorComponents.py
Testing command:
```Bash
docker exec semaphore-core python3 -m pytest ./src/tests/UnitTests/test_Average.py
```
I merged the vector components class because it was easier! Sorry about that
> 286 double location average post processing class for magnolia beach models

- tools/DatabaseMigration/2_2/2_2_DatabaseMigration.py
- tools/DatabaseMigration/2_2/init_data/virginiakeyLocations.csv
- tools/DatabaseMigration/2_2/init_data/virginiakeyMapping.csv
- tools/DatabaseMigration/target_version.json
The migration script for Beto's models!
> 2 2 migration

- data/dspec/Magnolia/12/magnolia_transform_12.json
We finalized the ranges for the transform 12 dspec
> Changed the ranges in the transform 12 dspec

- src/tests/UnitTests/test_dspecParser.py
Tests passing after directory updating tests to reflect directory
> Updating tests to reflect directory changes

- src/DataIngestion/DI_Classes/NDFD_EXP.py
- src/DataIngestion/DI_Classes/NOAATANDC.py
- src/SeriesProvider/SeriesProvider.py
Fixed shallow copy issues causing DB insertions to fail. Added sanity check to detect possible errors in expected DB insertions. Please read the ticket for more info.
Test procedure:
1. Start with fresh db `docker exec semaphore-core python3 tools/migrate_db.py`
2. Run a model using NOAATANDC. You should see DI instances here `docker exec semaphore-core python3 src/semaphoreRunner.py -d TestModels/test_dspec.json`
3. Running the same model again. You should NOT see any DI instances here.
4. Run a model using NDFD_EXP. You should see DI instances here. Might fail due to other NDFD issues `docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Aransas//ar_mlp_surge_12h_pred.json`
5. Run the same model. You should see DI instances only for dSurge, related to the other NOAATANDC …
> 421 db not saving multiple series inputs

- data/dspec/MLP-OP.json
Updating MLP-OP dspec to 2.0. 
To check this PR... its gonna suck. I wrote a checklist you can find here:
https://docs.google.com/spreadsheets/d/1eV9fRGkZnrJYPFxOCErO9p_oEVL2Mu1whJM-uyYW-30/edit?usp=sharing
Besides that its just comparing the old and new version determining no mistakes were made in the update. Sorry 😭
> Updating MLP-OP to DSPEC 2.0

- data/dspec/Magnolia/12/magnolia_12.json
- data/dspec/Surge/Aransas/ar_mlp_surge_12h_pred.json
- data/dspec/Surge/Aransas/ar_mlp_surge_24h_pred.json
- data/dspec/Surge/Aransas/ar_mlp_surge_48h_pred.json
- data/dspec/Surge/Aransas/ar_mlp_surge_72h_pred.json
- data/dspec/Surge/North_Jetty/nj_mlp_surge_12h_pred.json
- data/dspec/Surge/North_Jetty/nj_mlp_surge_24h_pred.json
- data/dspec/Surge/North_Jetty/nj_mlp_surge_48h_pred.json
- data/dspec/Surge/North_Jetty/nj_mlp_surge_72h_pred.json
- data/dspec/Surge/Port_Isabel/pi_mlp_surge_12h_pred.json
- data/dspec/Surge/Port_Isabel/pi_mlp_surge_24h_pred.json
- data/dspec/Surge/Port_Isabel/pi_mlp_surge_48h_pred.json
- data/dspec/Surge/Port_Isabel/pi_mlp_surge_72h_pred.json
- data/dspec/Surge/Rockport/rp_mlp_surge_12h_pred.json
- data/dspec/Surge/Rockport/rp_mlp_surge_24h_pred.json
- data/dspec/Surge/Rockport/rp_mlp_surge_48h_pred.json
- data/dspec/Surge/Rockport/rp_mlp_surge_72h_pred.json
- src/DataIngestion/DI_Classes/NOAATANDC.py
Updating thermal refuge dspec to 2.0. 
To check this PR... its gonna suck. I wrote a checklist you can find here:
https://docs.google.com/spreadsheets/d/1eV9fRGkZnrJYPFxOCErO9p_oEVL2Mu1whJM-uyYW-30/edit?usp=sharing
Besides that its just comparing the old and new version determining no mistakes were made in the update. Sorry 😭 
```
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Rockport/rp_mlp_surge_72h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Rockport/rp_mlp_surge_48h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Rockport/rp_mlp_surge_24h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Rockport/rp_mlp_surge_12h_pred.json -p …
```
> 438 update surge models to dspec 2.0

- src/ModelExecution/inputGatherer.py
- src/semaphoreRunner.py
You can test running multiple models like this:
```docker exec semaphore-core python3 src/semaphoreRunner.py -d ./VirginiaKey/12hr_VirginiaKey_wl_Estrada.json ./VirginiaKey/24hr_VirginiaKey_wl_Estrada.json```
> Adding in multi running models

- data/dspec/TestModels/test_indexing.json
- src/ModelExecution/dspecParser.py
- src/ModelExecution/inputGatherer.py
- src/tests/IntegrationTests/test_inputGatherer.py
- src/tests/UnitTests/test_dspecParser.py
Adding ordered vector indexing to index series passed to input gatherer. Added as optional parameter in DSPEC 2.0
Test:
Just build and run tests
> 485 make indexing possble in ordered vector

- tools/DatabaseMigration/2_9/2_9_DatabaseMigration.py
- tools/DatabaseMigration/2_9/init_data/lagunamadreMapping.csv
- tools/DatabaseMigration/target_version.json
The Coldstunning chart requires laguna madre datapoints from NDFD_EXP.
> Mapped laguna madre to ndfd_exp

- src/API/apiDriver.py
> Fixing API BUG

- tools/deploy.sh
See ticket for issues.
Updated deployment script to fetch and prune tags from origin, and then specifically checkout the tag that needs to be active.
> Updating deployment script to make it able to rollback

- src/API/apiDriver.py
This protects downstream products like flare and CBOCP from upstream changes by adding a custom serialize for the series object.
To test:
Run: `docker compose up --build -d`
Run: 
```bash
curl -X 'GET' \
'https://sherlock-dev.tamucc.edu/semaphore-api/input/source=NOAATANDC/series=dWl/location=Aransas/fromDateTime=2025032600/toDateTime=2025032603?datum=NAVD&interval=3600' \
-H 'accept: application/json' | python3 -m json.tool
```
Run:
```bash
curl -X 'GET' \
'https://localhost:8888/semaphore-api/input/source=NOAATANDC/series=dWl/location=Aransas/fromDateTime=2025032600/toDateTime=2025032603?datum=NAVD&interval=3600' \
-H 'accept: application/json' | python3 -m json.tool
```
Verify both outputs are identical
**NOTE:: This is bash code, so run it in wsl or git bash**
> Adding custome serializing

- src/SeriesStorage/SS_Classes/SQLAlchemyORM_Postgres.py
- Build the containers
- Go to this browser: http://localhost:8888/docs#/default/get_outputs_latest_output_latest__get
- Test output_latest with 'MRE_Bird-Island_Water-Temperature_3hr'
> The api can now handle an array of data from the database

- data/dspec/ColdStunning/Bird-Island_Water-Temperature_102hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_108hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_114hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_120hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_12hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_18hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_24hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_30hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_36hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_3hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_42hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_48hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_54hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_60hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_66hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_6hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_72hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_78hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_84hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_90hr.json
- data/dspec/ColdStunning/Bird-Island_Water-Temperature_96hr.json
- src/DataIngestion/DI_Classes/NDFD_API.py
- tools/DatabaseMigration/3_2/3_2_DatabaseMigration.py
- tools/DatabaseMigration/3_2/init_data/newRows.csv
- tools/DatabaseMigration/target_version.json
This pull request aims to solve the issue where interpolated values were stored in the database due to NDFD_EXP having some lines that automatically added interpolated values into the series in the ingestion class. 
More detials on the issue can be found in the following tickets from when we were investigating: 
- https://github.com/conrad-blucher-institute/semaphore/issues/620
- https://github.com/conrad-blucher-institute/semaphore/issues/602
We're aiming to fix this issue here by removing the block of code that addes the interpolated vaues in a new class that we call NDFD_API. This pull request creates that class, adds it as a source in the database, and changes the cold stunning models to use this new ingestion class rather than NDFD_EXP. 
To test you must first test the database …
> NDFD_API Class

- requirements.txt
Pin tensorflow version to 2.14.0
> Update tensorflow version specification
